[package]
name = "memory"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
rand = "0.8.5"
slint = "1.6"

[build-dependencies]
slint-build = "1.6"
